### ISSUE TITLE
Character animation without rigging

### ISSUE THREAD

**Issue by elkhalafy** [diegomacario/Animation-Magic#1]
How are you? 

I found Idea for character animation without rigs or bones. This idea created by pixar studios called character articulation through profile curves or Curvenent
They have been released the paper about this idea. 
So please if you able to do this As standalone Free application for Windows OS. It will be great

Look at the video and download the paper too

https://youtu.be/gUJ4RxMdVn8

Download the paper here :-

https://graphics.pixar.com/library/ProfileMover/paper.pdf

Please let me know, you will create it or not

Thank you

**Comment by elkhalafy** [comment]
Please answer

**Comment by diegomacario** [comment]
Closing, as follow-up happened in Animation-Experiments repo.
